#!/bin/sh
command -v git-lfs >/dev/null 2>&1 || { printf >&2 "\n%s\n\n" "This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting the 'post-checkout' file in the hooks directory (set by 'core.hookspath'; usually '.git/hooks')."; exit 2; }
git lfs post-checkout "$@"

#!/bin/bash
export PATH="$PATH:/opt/homebrew/bin"

# ignores updates of 'Secrets.swift' to avoid pushing sensitive data by mistake
git update-index --assume-unchanged Components/Secrets/Secrets.swift

LOCAL_SCRIPT_PATH="$HOME/.local/elementx_local_dev/post-checkout"
if [ -x "$LOCAL_SCRIPT_PATH" ]; then
	export ELEMENTX_REPO="$(pwd)"
	"$LOCAL_SCRIPT_PATH"
fi
