#!/bin/sh
command -v git-lfs >/dev/null 2>&1 || { printf >&2 "\n%s\n\n" "This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting the 'pre-push' file in the hooks directory (set by 'core.hookspath'; usually '.git/hooks')."; exit 2; }
git lfs pre-push "$@"

LOCAL_SCRIPT_PATH="$HOME/.local/elementx_local_dev/pre-push"
if [ -x "$LOCAL_SCRIPT_PATH" ]; then
	export ELEMENTX_REPO="$(pwd)"
	"$LOCAL_SCRIPT_PATH"
fi
