project: ElementX.xcodeproj
schemes:
- ElementX
- IntegrationTests
- UITests
- UnitTests
targets:
- ElementX
- IntegrationTests
- NCE
- NSE
- UITests
- UnitTests
verbose: true
retain_swift_ui_previews: true
