project: ElementX.xcodeproj
schemes:
- ElementX
- IntegrationTests
- UITests
- UnitTests
- PreviewTests
targets:
- ElementX
- IntegrationTests
- NSE
- PreviewTests
- UITests
- UnitTests
report_exclude:
  - ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  - ElementX/Sources/Mocks/Generated/SDKGeneratedMocks.swift
verbose: true
retain_swift_ui_previews: true
