disabled_rules:
  - trailing_whitespace
  - unused_setter_value
  - redundant_discardable_let
  - identifier_name

opt_in_rules:  
  - force_unwrapping
  - private_action
  - explicit_init
  - shorthand_optional_binding

included:
  - ElementX
  - UnitTests
  - UITests
  - Tools/Scripts/Templates
excluded:
  - IntegrationTests

line_length:
  warning: 250
  error: 1000

file_length:
  warning: 800
  error: 1000

type_name:
  min_length: 3
  max_length:
    warning: 150
    error: 1000

type_body_length:
  warning: 700
  error: 1000

function_body_length:
  warning: 50
  error: 100

nesting:
  type_level:
    warning: 5

custom_rules:
  print_deprecation:
    regex: "\\b(print)\\b"
    match_kinds: identifier
    message: "MXLog should be used instead of print()"
    severity: error

  print_ln_deprecation:
    regex: "\\b(println)\\b"
    match_kinds: identifier
    message: "MXLog should be used instead of println()"
    severity: error

  os_log_deprecation:
    regex: "\\b(os_log)\\b"
    match_kinds: identifier
    message: "MXLog should be used instead of os_log()"
    severity: error
