settings:
  APP_DISPLAY_NAME: TULPAR
  PRODUCTION_APP_NAME: TULPAR
  APP_GROUP_IDENTIFIER: group.kz.tulpar.chat
  BASE_BUNDLE_IDENTIFIER: kz.tulpar.chat
  ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: "colors/accent-color"
  DEVELOPMENT_TEAM: 7J4U792NQT
