settings:
  APP_DISPLAY_NAME: Element X
  PRODUCTION_APP_NAME: Element
  BASE_APP_GROUP_IDENTIFIER: com.sinch.rtc.giober-test
  BASE_BUNDLE_IDENTIFIER: com.sinch.rtc.giober-test
  ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: "colors/accent-color"
  DEVELOPMENT_TEAM: 589CW2BWK2
