settings:
  APP_DISPLAY_NAME: Element X
  PRODUCTION_APP_NAME: Element
  APP_GROUP_IDENTIFIER: group.io.element
  CLASSIC_APP_GROUP_IDENTIFIER: group.im.vector
  BASE_BUNDLE_IDENTIFIER: io.element.elementx
  CLASSIC_APP_BUNDLE_IDENTIFIER: im.vector.app
  ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: "colors/accent-color"
  DEVELOPMENT_TEAM: 7J4U792NQT
