settings:
  APP_DISPLAY_NAME: SevenChat
  PRODUCTION_APP_NAME: SevenChat
  APP_GROUP_IDENTIFIER: group.io.sevenchat
  BASE_BUNDLE_IDENTIFIER: io.sevenchat.sevenchat
  ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: "colors/accent-color"
  DEVELOPMENT_TEAM: 7J4U792NQT
