settings:
  APP_DISPLAY_NAME: VoiceDrop
  PRODUCTION_APP_NAME: VoiceDrop
  BASE_APP_GROUP_IDENTIFIER: test.voicedrop
  BASE_BUNDLE_IDENTIFIER: test.voicedrop
  ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: "colors/accent-color"
  DEVELOPMENT_TEAM: L9RH9A4FX5
