settings:
  APP_DISPLAY_NAME: Element X
  PRODUCTION_APP_NAME: Element
  BASE_APP_GROUP_IDENTIFIER: io.element
  BASE_BUNDLE_IDENTIFIER: io.element.elementx
  ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: "colors/accent-color"
  DEVELOPMENT_TEAM: 7J4U792NQT