settings:
  APP_DISPLAY_NAME: Dev Tchap X
  PRODUCTION_APP_NAME: Tchap
  BASE_APP_GROUP_IDENTIFIER: fr.gouv.tchap
  BASE_BUNDLE_IDENTIFIER: fr.gouv.tchapx.dev
  ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: "colors/accent-color"
  DEVELOPMENT_TEAM: NVMQD635C6
