settings:
  APP_DISPLAY_NAME: Gua
  PRODUCTION_APP_NAME: Gua
  APP_GROUP_IDENTIFIER: sarahlacerda.me.gua
  BASE_BUNDLE_IDENTIFIER: me.sarahlacerda.gua
  ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: "colors/accent-color"
  DEVELOPMENT_TEAM: 3HD49L7PSA
  DEFAULT_ACCOUNT_PROVIDER: dev.gua.sarahlacerda.me
  OIDC_REDIRECT_URL: me.sarahlacerda.gua://oidc
  OIDC_STATIC_REGISTRATIONS: ""
