coverage:
  status:
    project:
      default:
        # Commits pushed to master should not make the overall
        # project coverage decrease by more than 1%:
        target: auto
        threshold: 1%
    patch: false

ignore:
  - "ElementX/Sources/Generated"
  - "ElementX/Sources/Mocks"
  - "ElementX/Sources/Vendor"
  - "ElementX/Sources/UITests"
  - "ElementX/Sources/UnitTests"
  - "ElementX/Sources/Settings/DeveloperOptionsScreen"
  - "Tools"
  - "**/Mock*.swift"
  - "**/*Mock.swift"
  - "**/*Proxy.swift"

flag_management:
  default_rules:
    carryforward: true
    statuses:
      - name_prefix: project-
        type: project
        target: auto
        threshold: 1%