name: ElementX
attributes:
  ORGANIZATIONNAME: Element

fileGroups:
    - project.yml

options:
  groupSortPosition: bottom
  createIntermediateGroups: true
  deploymentTarget:
    iOS: "15.0"
    macOS: "12.0"
  groupOrdering: 
    - order: [ElementX, UnitTests, UITests, Tools]
    - pattern: ElementX
      order: [Sources, Resources, SupportingFiles]
    - pattern: Sources
      order: [Services, Screens, Other]

settings:
  CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: YES
  ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: "Colors/ElementGreen"
  ENABLE_BITCODE: NO


include:
  - path: ElementX/SupportingFiles/target.yml
  - path: UnitTests/SupportingFiles/target.yml
  - path: UITests/SupportingFiles/target.yml

packages:
  MatrixRustSDK:
    url: https://github.com/matrix-org/matrix-rust-components-swift.git
    branch: main
  DTCoreText:
    url: https://github.com/Cocoanetics/DTCoreText
    majorVersion: 1.6.26
  KeychainAccess:
    url: https://github.com/kishikawakatsumi/KeychainAccess
    majorVersion: 4.2.2
  Kingfisher:
    url: https://github.com/onevcat/Kingfisher
    majorVersion: 7.2.0
  Introspect:
    url: https://github.com/siteline/SwiftUI-Introspect.git
    majorVersion: 0.1.4
  SwiftyBeaver:
    url: https://github.com/SwiftyBeaver/SwiftyBeaver
    majorVersion: 1.9.5
  SwiftState:
    url: https://github.com/ReactKit/SwiftState
    majorVersion: 6.0.0
