name: ElementX
attributes:
  ORGANIZATIONNAME: Element

fileGroups:
    - project.yml

options:
  groupSortPosition: bottom
  createIntermediateGroups: true
  deploymentTarget:
    iOS: "16.4"
    macOS: "13.3"
  groupOrdering: 
    - order: [ElementX, UnitTests, UITests, IntegrationTests, Tools]
    - pattern: ElementX
      order: [Sources, Resources, SupportingFiles]
    - pattern: Sources
      order: [Application, UserSession, Services, FlowCoordinators, Screens, Other, UITests]
  postGenCommand: cd Tools/XcodeGen && sh postGenCommand.sh

settings:
  CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: YES
  ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: "Colors/AccentColor"
  ENABLE_BITCODE: NO
  BASE_APP_GROUP_IDENTIFIER: io.element
  APP_GROUP_IDENTIFIER: group.$(BASE_APP_GROUP_IDENTIFIER)
  BASE_BUNDLE_IDENTIFIER: io.element.elementx
  KEYCHAIN_ACCESS_GROUP_IDENTIFIER: $(AppIdentifierPrefix)$(BASE_BUNDLE_IDENTIFIER)
  MARKETING_VERSION: 1.1.2
  CURRENT_PROJECT_VERSION: 1
  DEVELOPMENT_TEAM: 7J4U792NQT

include:
  - path: ElementX/SupportingFiles/target.yml
  - path: UnitTests/SupportingFiles/target.yml
  - path: UITests/SupportingFiles/target.yml
  - path: IntegrationTests/SupportingFiles/target.yml
  - path: NSE/SupportingFiles/target.yml
  - path: NCE/SupportingFiles/target.yml

packages:
  MatrixRustSDK:
    url: https://github.com/matrix-org/matrix-rust-components-swift
    exactVersion: 1.0.72-alpha
    # path: ../matrix-rust-sdk
  DesignKit:
    path: DesignKit
  Compound:
    url: https://github.com/vector-im/compound-ios
    revision: aaa43409ca09130cb9e9a0fe02c803c65aa42aed
    # path: ../compound-ios
  Algorithms:
    url: https://github.com/apple/swift-algorithms
    minorVersion: 1.0.0
  AnalyticsEvents:
    url: https://github.com/matrix-org/matrix-analytics-events
    minorVersion: 0.5.0
  Collections:
    url: https://github.com/apple/swift-collections
    minorVersion: 1.0.0
  DeviceKit:
    url: https://github.com/devicekit/DeviceKit
    minorVersion: 5.0.0
  DTCoreText:
    url: https://github.com/Cocoanetics/DTCoreText
    exactVersion: 1.6.26
  KeychainAccess:
    url: https://github.com/kishikawakatsumi/KeychainAccess
    minorVersion: 4.2.0
  Kingfisher:
    url: https://github.com/onevcat/Kingfisher
    minorVersion: 7.6.0
  KZFileWatchers:
    url: https://github.com/krzysztofzablocki/KZFileWatchers
    branch: master
  Introspect:
    url: https://github.com/siteline/SwiftUI-Introspect
    minorVersion: 0.2.0
  PostHog:
    url: https://github.com/PostHog/posthog-ios
    minorVersion: 2.0.3
  SwiftState:
    url: https://github.com/ReactKit/SwiftState
    minorVersion: 6.0.0
  GZIP:
    url: https://github.com/nicklockwood/GZIP
    minorVersion: 1.3.0
  Sentry:
    url: https://github.com/getsentry/sentry-cocoa
    minorVersion: 8.6.0
  SnapshotTesting:
    url: https://github.com/pointfreeco/swift-snapshot-testing
    minorVersion: 1.11.0
  URLRouting:
    url: https://github.com/pointfreeco/swift-url-routing
    minorVersion: 0.5.0
  Version:
    url: https://github.com/mxcl/Version
    minorVersion: 2.0.0
