name: ElementX
attributes:
  ORGANIZATIONNAME: Element

fileGroups:
    - project.yml

options:
  groupSortPosition: bottom
  createIntermediateGroups: true
  deploymentTarget:
    iOS: "16.0"
    macOS: "13.0"
  groupOrdering: 
    - order: [ElementX, UnitTests, UITests, IntegrationTests, Tools]
    - pattern: ElementX
      order: [Sources, Resources, SupportingFiles]
    - pattern: Sources
      order: [Application, UserSession, Services, Screens, Other, UITests]
  postGenCommand: cd Tools/XcodeGen && sh postGenCommand.sh

settings:
  CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: YES
  ENABLE_BITCODE: NO
  BASE_APP_GROUP_IDENTIFIER: io.element
  APP_GROUP_IDENTIFIER: group.$(BASE_APP_GROUP_IDENTIFIER)
  BASE_BUNDLE_IDENTIFIER: io.element.elementx
  KEYCHAIN_ACCESS_GROUP_IDENTIFIER: $(AppIdentifierPrefix)$(BASE_BUNDLE_IDENTIFIER)
  MARKETING_VERSION: 1.0.25
  CURRENT_PROJECT_VERSION: 1
  DEVELOPMENT_TEAM: 7J4U792NQT

include:
  - path: ElementX/SupportingFiles/target.yml
  - path: UnitTests/SupportingFiles/target.yml
  - path: UITests/SupportingFiles/target.yml
  - path: IntegrationTests/SupportingFiles/target.yml
  - path: NSE/SupportingFiles/target.yml

packages:
  MatrixRustSDK:
    url: https://github.com/matrix-org/matrix-rust-components-swift
    exactVersion: 1.0.46-alpha
    # path: ../matrix-rust-sdk
  DesignKit:
    path: DesignKit
  Algorithms:
    url: https://github.com/apple/swift-algorithms
    majorVersion: 1.0.0
  AnalyticsEvents:
    url: https://github.com/matrix-org/matrix-analytics-events
    exactVersion: 0.4.0
  AppAuth:
    url: https://github.com/openid/AppAuth-iOS
    majorVersion: 1.5.0
  Collections:
    url: https://github.com/apple/swift-collections
    majorVersion: 1.0.4
  DeviceKit:
    url: https://github.com/devicekit/DeviceKit
    majorVersion: 4.7.0
  DTCoreText:
    url: https://github.com/Cocoanetics/DTCoreText
    majorVersion: 1.6.26
  KeychainAccess:
    url: https://github.com/kishikawakatsumi/KeychainAccess
    majorVersion: 4.2.2
  Kingfisher:
    url: https://github.com/onevcat/Kingfisher
    majorVersion: 7.2.0
  KZFileWatchers:
    url: https://github.com/krzysztofzablocki/KZFileWatchers
    branch: master
  Introspect:
    url: https://github.com/siteline/SwiftUI-Introspect
    majorVersion: 0.2.3
  PostHog:
    url: https://github.com/PostHog/posthog-ios
    majorVersion: 1.4.4
  SwiftyBeaver:
    url: https://github.com/SwiftyBeaver/SwiftyBeaver
    majorVersion: 1.9.5
  SwiftState:
    url: https://github.com/ReactKit/SwiftState
    majorVersion: 6.0.0
  GZIP:
    url: https://github.com/nicklockwood/GZIP
    majorVersion: 1.3.0
  Sentry:
    url: https://github.com/getsentry/sentry-cocoa
    majorVersion: 7.15.0
  SnapshotTesting:
    url: https://github.com/pointfreeco/swift-snapshot-testing
    majorVersion: 1.10.0
  Version:
    url: https://github.com/mxcl/Version
    majorVersion: 2.0.1
