sources:
  include:
    - ../../ElementX
  exclude:
    - ../../ElementX/Sources/Mocks/SDK
templates:
  - AutoMockable.stencil
output:
  ../../ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
args:
  automMockableTestableImports: []
  autoMockableImports: [Combine, Foundation, SwiftUI, AnalyticsEvents, MatrixRustSDK]
