sources:
  include:
    - ../../ElementX
  exclude:
    - ../../ElementX/Sources/Mocks/SDK
templates:
  - AutoMockable.stencil
output:
  ../../ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
args:
  automMockableTestableImports: []
  autoMockableImports: [AnalyticsEvents, Combine, Foundation, LocalAuthentication, MatrixRustSDK, SwiftUI]
