input_dir: ../../TchapX/main/
output_dir: ../../TchapX/main/Sources/Generated/
xcassets:
  inputs:
    - Resources/Assets.xcassets
  outputs:
    templateName: swift5
    output: TchapAssets.swift
    params:
      enumName: TchapAssets # To not conflict with ElementX/Assets.swift
      colorTypeName: TchapColor # To not conflict with ElementX/Assets.swift
      colorAliasName: TchapAssetColorTypeAlias # To not conflict with ElementX/Assets.swift
      imageTypeName: TchapImage # To not conflict with ElementX/Assets.swift
      imageAliasName: TchapAssetImageTypeAlias # To not conflict with ElementX/Assets.swift
strings:
  - inputs: Resources/Localizations/en.lproj
    filter: TchapLocalizable*
    outputs:
      templatePath: Templates/Strings/structured-swift5-element.stencil
      output: TchapStrings.swift
      params:
        enumName: TchapL10n
        lookupFunction: tr  # used for the loc to be computed variables
        publicAccess: false
  - inputs: Resources/Localizations/en.lproj
    filter: TchapUntranslated*
    outputs:
      templatePath: Templates/Strings/structured-swift5-element-untranslated.stencil
      output: TchapStrings+Untranslated.swift
      params:
        enumName: TchapUntranslatedL10n
        lookupFunction: tr  # used for the loc to be computed variables
        publicAccess: false
