name: Danger CI

on:
  pull_request:
    types: [labeled, synchronize, opened, reopened]

permissions: {}

jobs:
  build:
    name: Danger
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      pull-requests: write # The token is still read-only for forks.
      statuses: write

    concurrency:
      # Only allow a single run of this workflow on each branch, automatically cancelling older runs.
      group: ${{ format('danger-ci-{0}', github.ref) }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Danger
        uses: danger/swift@751aa740b2bd69ea1b54444a945961e64c38fc22 # 3.22.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
