name: Tests

on:
  push:
    branches: [ develop ]
  pull_request:

jobs:
  tests:
    name: Tests
    runs-on: macos-12

    concurrency:
      # When running on develop, use the sha to allow all runs of this workflow to run concurrently.
      # Otherwise only allow a single run of this workflow on each branch, automatically cancelling older runs.
      group: ${{ github.ref == 'refs/heads/develop' && format('tests-develop-{0}', github.sha) || format('tests-{0}', github.ref) }}
      cancel-in-progress: true

    steps:
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.4.1
        with:
          xcode-version: '13.4'

      - uses: actions/checkout@v3
        with:
          lfs: true

      - uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      
      - name: Run tests
        run: bundle exec fastlane tests
      
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: xcode-test-result
          path: ${{ env.SCAN_GENERATED_XCRESULT_PATH }}
          retention-days: 7
          if-no-files-found: ignore

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3