name: Move labelled issues to correct boards and columns

on:
  issues:
    types: [labeled]

jobs:
  ex_plorers:
    name: Add labelled issues to X-Plorer project
    runs-on: ubuntu-latest
    if: >
      contains(github.event.issue.labels.*.name, 'Team: Element X Feature')
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/element-hq/projects/73
          github-token: ${{ secrets.ELEMENT_BOT_TOKEN }}

  verticals_feature:
    name: Add labelled issues to Verticals Feature project
    runs-on: ubuntu-latest
    if: >
      contains(github.event.issue.labels.*.name, 'Team: Verticals Feature')
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/element-hq/projects/57
          github-token: ${{ secrets.ELEMENT_BOT_TOKEN }}

  platform:
    name: Add labelled issues to EX project
    runs-on: ubuntu-latest
    if: >
      contains(github.event.issue.labels.*.name, 'Team: Element X Platform')
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/element-hq/projects/43
          github-token: ${{ secrets.ELEMENT_BOT_TOKEN }}

  qa:
    name: Add labelled issues to QA project
    runs-on: ubuntu-latest
    if: >
      contains(github.event.issue.labels.*.name, 'Team: QA') ||
      contains(github.event.issue.labels.*.name, 'X-Needs-Signoff')
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/element-hq/projects/69
          github-token: ${{ secrets.ELEMENT_BOT_TOKEN }}

  signoff:
    name: Add labelled issues to signoff project
    runs-on: ubuntu-latest
    if: >
      contains(github.event.issue.labels.*.name, 'X-Needs-Signoff')
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/element-hq/projects/89
          github-token: ${{ secrets.ELEMENT_BOT_TOKEN }}
