name: Validate Git LFS

on:
  workflow_dispatch:
  
  schedule:
    - cron:  '0 0 * * 1-5'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Validate
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: 'true'

      - run: |
          ./Tools/Scripts/validate_lfs.sh
